version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: jdungeon-web-gateway
    container_name: jdungeon-web-gateway
    restart: always
    volumes:
      - /etc/letsencrypt/live/jdungeon.org/fullchain.pem:/etc/letsencrypt/live/jdungeon.org/fullchain.pem
      - /etc/letsencrypt/live/jdungeon.org/privkey.pem:/etc/letsencrypt/live/jdungeon.org/privkey.pem
    network_mode: "host"
